LOAD DATA
CHARACTERSET UTF8
INFILE *
APPEND
INTO TABLE MIK_OCF_DETAIL_TBL
WHEN (1:1) = 'D'
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(
  DETAIL_INDICATOR          CHAR(10),
  VENDOR_NUMBER             CHAR(50),
  PO_NUMBER                 CHAR(50) "'MCF' || :PO_NUMBER",
  ITEM_NUMBER               CHAR(100),
  ITEM_DESCRIPTION          CHAR(200),
  SALES_RETURN_INDICATOR    CHAR(100),
  PRODUCT_TYPE              CHAR(20),
  COUPON_TXT                CHAR(100),
  SHIPMENT_MODE             CHAR(100),
  SHIPPED_TO_LOCATION       CHAR(100),
  DELIVERY_TRACKING_CODE    CHAR(100),
  CONFIRMED_RECEIPT_DATE    CHAR(20),
  SHIP_TO_STATE             CHAR(50),
  NUMBER_OF_UNITS           CHAR(50),
  COST_PRICE                CHAR(50),
  RETAIL_PRICE              CHAR(50),
  DISCOUNT_AMOUNT           CHAR(50),
  NET_AMOUNT                CHAR(50),
  SALES_TAX                 CHAR(50),
  SERVICE_TAX               CHAR(50),
  ADDITIONAL_TAX            CHAR(50),
  HANDLING_FEE              CHAR(50),
  COGS                      CHAR(50),
  SHIPPING_COST             CHAR(50),
  SHIPPING_REVENUE          CHAR(50),
  PRODUCT_CLASS             CHAR(20),
  TAX_BUCKET                CHAR(20),
  RETAIL_COST_FLAG          CHAR(20),
  DESCRIPTION               CHAR(1000),
  MEMBERSHIP_SALE_DATE      CHAR(100),
  MEMBERSHIP_BEGIN_DATE     CHAR(100),
  MEMBERSHIP_END_DATE       CHAR(100),
  SHIP_TO_COUNTRY           CHAR(50),
  INSERTTIME                SYSDATE
)

